# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='fakeness',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statement',
            name='usersvote',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statement',
            name='usersvoteFake',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
