# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20170330_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='usersvoteTrue',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
