# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_statement_usersvotetrue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statement',
            name='usersvote',
        ),
    ]
