# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_statement_usersvote'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('image', models.URLField()),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Statement')),
            ],
        ),
    ]
