# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 21:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statement',
            name='description',
        ),
    ]
