# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20170503_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='tags',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='statement',
            name='fakeness',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statement',
            name='usersvoteFake',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statement',
            name='usersvoteTrue',
            field=models.IntegerField(default=0),
        ),
    ]
